apiVersion: v1
kind: Service
metadata:
  name: k8s-monitoring
  namespace: minilab
  labels:
    app: k8s-monitoring
spec:
  selector:
    app: k8s-monitoring
  ports:
    - name: http
      port: 8080
      targetPort: 8080
