apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-svcmonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}
  endpoints:
    - port: monitor
      path: /metrics
      interval: 15s
