apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-crole
  annotations:
    owner: "Seob"
    description: "Only for Monitoring Application"
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
