apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deploy
  namespace: {{ .Release.Namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.label }}
    spec:
      serviceAccountName: {{ .Release.Name }}-svcacc
      containers:
        - name: k8s-monitoring
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: {{ .Values.container.port}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.container.port }}
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.container.port }}
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
