apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.label }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.label }}
  ports:
    - name: monitor
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
