replicaCount: 3

image:
  repository: ghcr.io/dandapss/helm-monitor
  tag: 4fdcd1fb2fed37c4dab27e7fc81c5f74884c9813

app:
  label: k8s-resource-monitoring

container:
  port: 8080

service:
  port: 9090
