replicaCount: 3

image:
  repository: ghcr.io/dandapss/helm-monitor
  tag: d1fb24ff850359593c97ad864e8a72eee07154d5

app:
  label: k8s-resource-monitoring

container:
  port: 8080

service:
  port: 9090
