replicaCount: 3

image:
  repository: ghcr.io/dandapss/helm-monitor
  tag: c8d4a8a77d5ce68d00627ad813c8c655407be54e

app:
  label: k8s-resource-monitoring

container:
  port: 8080

service:
  port: 9090
