name: Work Flow Practice

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Dockerfile
        run: test -f Dockerfile
      - name: Show files
        run: ls -la
        
      - name: Build Image
        run: docker build -t custom-exporter:test .
      - name: Build Image-Fail
        if: failure()
        run: echo "build process failed!"
